### ISSUE TITLE
(Решение) Баг нативной библиотеки (Java_ru_yandex_core_CoreApplication_init+552)

### ISSUE THREAD

**Issue by Mikhail-dev** [yandexmobile/yandexmapkit-android#183]
Если вдруг у вас упало что-то в нативной библиотеки, наподобие этого 

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/vivalto3gxx/vivalto3g:4.4.2/KOT19H/G678HXXU0ANJ4:user/release-keys'
Revision: '0'
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
r0 00000000 r1 00000e8c r2 00000006 r3 00000000
r4 00000006 r5 00000002 r6 00000e8c r7 0000010c
r8 ba90001d r9 4c648870 sl 415de6d0 fp bee972b4
ip bee96d2c sp bee96970 lr 400ea07d pc 400f8fb4 cpsr 000f0010
d0 74726f6261204d56 d1 617453657669746e
d2 4965746f67795a75 d3 6e69616d2e74696c
d4 65646e61592e7374 d5 6761724670614d78
d6 436e6f2e746e656d d7 6569566574616572
d8 0000000000000000 d9 0000000000000000
d10 0000000000000000 d11 0000000000000000
d12 0000000000000000 d13 0000000000000000
d14 0000000000000000 d15 0000000000000000
d16 3fb4f219e06d4b4a d17 0000000000000004
d18 bfc9c11701e1b0d8 d19 3fd56eb44fff94eb
d20 3fc54f7eedde28a9 d21 bf66b887135d4c23
d22 3fb130a3254c05f6 d23 3fba8fc2a3f9e8c2
d24 3f860c2222af8b4a d25 3fa99245faeecc69
d26 3f90ad3ae322da11 d27 bfae11b96c8e9f2f
d28 3fb7752d9840a6b8 d29 bfa2b4442c6a6c2f
d30 bfb3da61dbdbc98b d31 3fc269777a9fea57
scr 60000011

backtrace:
#00 pc 00021fb4 /system/lib/libc.so (tgkill+12)
#01 pc 00013079 /system/lib/libc.so (pthread_kill+48)
#02 pc 0001328d /system/lib/libc.so (raise+10)
#03 pc 00011fc1 /system/lib/libc.so
#04 pc 00021868 /system/lib/libc.so (abort+4)
#05 pc 00045cb3 /system/lib/libdvm.so (dvmAbort+78)
#06 pc 0004a4e7 /system/lib/libdvm.so (dvmDecodeIndirectRef(Thread*, _jobject*)+146)
#07 pc 0004b4bd /system/lib/libdvm.so
#08 pc 00042bd0 /data/app-lib/ru.pkgname.appname-1/libcache_local.so (getRootForFileSystem(int, char*)+112)
#09 pc 00042c84 /data/app-lib/ru.pkgname.appname-1/libcache_local.so (mountSharedFileSystem(bool)+120)
#10 pc 00042eb8 /data/app-lib/ru.pkgname.appname-1/libcache_local.so (palFileSystemInit()+304)
#11 pc 0004788c /data/app-lib/ru.pkgname.appname-1/libcache_local.so (palGlobalInit()+4)
#12 pc 00043144 /data/app-lib/ru.pkgname.appname-1/libcache_local.so (Java_ru_yandex_core_CoreApplication_init+552)
#13 pc 0001dd4c /system/lib/libdvm.so (dvmPlatformInvoke+112)
#14 pc 0004dfc7 /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+394)
#15 pc 0004f98d /system/lib/libdvm.so (dvmResolveNativeMethod(unsigned int const*, JValue*, Method const*, Thread*)+184)
#16 pc 00027160 /system/lib/libdvm.so
#17 pc 0002e0a8 /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#18 pc 0002b754 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#19 pc 0006069d /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
#20 pc 00067de7 /system/lib/libdvm.so
#21 pc 00027160 /system/lib/libdvm.so
#22 pc 0002e0a8 /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#23 pc 0002b754 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#24 pc 0006069d /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
#25 pc 000685b3 /system/lib/libdvm.so
#26 pc 00027160 /system/lib/libdvm.so
#27 pc 0002e0a8 /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#28 pc 0002b754 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#29 pc 000603bb /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+338)
#30 pc 00049c17 /system/lib/libdvm.so
#31 pc 00051a37 /system/lib/libandroid_runtime.so

code around pc:
400f8f94 e8bd00f0 e3700a01 912fff1e e2600000 
400f8fa4 ea006ec2 e92d50f0 e3a07f43 ef000000 
400f8fb4 e8bd50f0 e3700a01 912fff1e e2600000 
400f8fc4 ea006eba e92d50f0 e3a070ee ef000000 
400f8fd4 e8bd50f0 e3700a01 912fff1e e2600000 
400f8fe4 ea006eb2 e1520003 8a00008c f5d1f040 
400f8ff4 e92d4001 e3520010 3a000024 e2603000 
400f9004 e213300f 0a00000e e0422003 e1b0cf83 
400f9014 44d1e001 44c0e001 24d1c001 24d1e001 
400f9024 24c0c001 24c0e001 e1b0ce83 aa000001 
400f9034 f4a1030d f480031d 3a000001 f421070d 
400f9044 f400071d e2522040 3a000006 f421020d 
400f9054 f421420d f5d1f100 e2522040 f400022d 
400f9064 f400422d 2afffff8 e2922020 3a000002 
400f9074 f421020d e2422020 f400022d e2822020 
400f9084 e3120010 0a000001 f4210a0d f4000a2d 

code around lr:
400ea05c 447b4b13 42b3e010 4812d10e 44786a1e 
400ea06c ec9ef7fb e9d4f00d 46224631 ef96f00e 
400ea07c d00a3001 e00b2400 2b00681b 480ad1eb 
400ea08c 44782403 ec8cf7fb f001e002 6804fa1b 
400ea09c fa18f001 46206005 bf00bd70 0003b346 
400ea0ac 0003b33a 0003b332 0003b30e bf7ef7ff 
400ea0bc 43f0e92d 4a3d4b3c 589c447b 6823b08b 
400ea0cc 460d4606 f0019309 46a1f9fd 8000f8d0 
400ea0dc d0482d00 f00f4628 280ffe67 d8444604 
400ea0ec ffe4f7ff d1064286 4629200f e89ef00d 
400ea0fc d03c2800 482ee02e f7fb4478 482debd4 
400ea10c e0154478 d11342b0 482b6a06 f7fb4478 
400ea11c 4a2aec48 447a2120 a8014633 f9fef013 
400ea12c a8012101 fd00f01a 46061c42 e011d104 
400ea13c 28006800 e02cd1e6 46294630 f00d4622 
400ea14c 1c43e8da d11e4607 f9bcf001 29046801 

то с большой долей вероятности падение происходит из-за того, что либа пытается записать что-то куда-то, но так как прав на это дело нет, то падает. Добавьте себе  
android.permission.WRITE_SETTINGS

Падать начинает только на тех устройствах, где никогда не были до этого запущены Яндекс карты (либо возможно Яндекс навигатор)

**Comment by mksaint13** [comment]
Данная  бага была  закрыта  в новой версии.
