### ISSUE TITLE
Падение приложения при запуске

### ISSUE THREAD

**Issue by martinjack** [yandexmobile/yandexmapkit-android#192]
Подключил библиотеку в IDEA как обычно. И при запуске приложения получаю вот такую ошибку :
Caused by: java.lang.UnsatisfiedLinkError: Couldn't load cache: findLibrary returned null. Как устранить её ??

**Comment by seelts** [comment]
@martinjack 
Мне помогло поднятие minSdkVersion в библиотеке. Сделал такой же как и у основного проекта.

**Comment by martinjack** [comment]
У то же также делал нечего ( Та же ошибка при старте приложения. Вот думаю может кто то сможет пересобрать  библиотеку. Или даже скинет готовую. 
И когда уже они обновлять её, надоело ждать. Работы тормозиться  зря

**Comment by martinjack** [comment]
Решил проблему)) Хоть и прошло не мало времени. Библиотеку получилось поднять только в Android Studio. 
Как это получилось :
1)File->Project Structure->Жмём "+"->Import Existing Project->Next->Source directory->Выбираем yandexmapkit-library.->Next->Finish; Теперь ждём пока пройдёт проверка и загрузка файлов. После удачном импорте получите сообщение. Дальше
2)File->Project Structure->Выбираем наш проект->Dependencies- Жмём"+"->Module dependency->Выбираем библиотеку(:yandexmapkitlibrary)->OK->OK;После этого карта yandex заработает. 
Всем удачи!!
P.S не забываем указать все права для карты в манифесте!
P.S.S возможно сработает такой вариант импорта и в Intellij IDEA.
