### ISSUE TITLE
How to import yandexmapkit-android into android studio

### ISSUE THREAD

**Issue by anilustel** [yandexmobile/yandexmapkit-android#199]
Hey!!

How to integrate yandexmapkit-android project into my android studio project?
I think yanexmapkit-android project is a eclipse project because of that I couldn't open it as a Android Studio project. because of gradle :(

Could you help me plzz?

**Comment by mikesmth** [comment]
Read this thread with chrome (translates): 
https://github.com/yandexmobile/yandexmapkit-android/issues/129

**Comment by livotov** [comment]
You can try my fork where I repackaged it into gradle and put aar tto a maven repo - https://github.com/livotov/yandexmapkit-android

Hope this helps

**Comment by mksaint13** [comment]
allprojects {
    repositories {
        jcenter()
        maven { url 'https://github.com/yandexmobile/yandexmapkit-android/raw/maven/' }
    }
}

dependencies {
    compile 'ru.yandex:yandexmapkit:2.4.0@aar'
}
