### ISSUE TITLE
Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by PetrBe** [yandexmobile/yandexmapkit-android#203]
Здравствуйте! 
При перемещении по карте часто происходит крэш приложения:

12-29 09:50:04.436 6905-7990/? E/MmapManager: segv_handler called: sig 11, si_addr 0x7f5eaa7e; si_errno 0; si_code 1
12-29 09:50:04.446 6905-7990/? A/libc: Fatal signal 11 (SIGSEGV), thread 7990 (ymm-main)
12-29 09:50:05.407 1188-8020/? E/android.os.Debug: !@Dumpstate > dumpstate -k -t -z -d -o /data/log/dumpstate_app_error

Проблема в нативной библиотеке, и перехватить это средствами Java нельзя. Считаем проблему критической. Можем ли ожидать ее решения в ближайшее время? 

[dumpstate.txt](https://github.com/yandexmobile/yandexmapkit-android/files/73784/dumpstate.txt)

**Comment by livotov** [comment]
думаю, надеяться особо смысла нет - они, похоже, забили совсем :(

**Comment by mksaint13** [comment]
Данная  ошибка исправлена в  новой версии.
