### ISSUE TITLE
Balloon сменить цвет текста

### ISSUE THREAD

**Issue by shwalabaka** [yandexmobile/yandexmapkit-android#205]
Запускаю тестовое приложение, демонстрирующее возможности Yandex Map Kit -- yandexmapkit-sample. В примере стандартный балун цвет текста совпадает с цветом балуна.

**Comment by mksaint13** [comment]
Балун вы  можете  менять на ваше  усмотрение.  Есть уже множество приложений например  https://play.google.com/store/apps/details?id=com.edadeal.android

**Comment by shwalabaka** [comment]
http://stackoverflow.com/questions/35985844/yandex-mapkit-android-balloon-set-text-color

**Comment by mxl** [comment]
@mksaint13 Каким образом я могу менять балун? Ответ @shwalabaka не работает. Можно каким-то образом сделать `BalloonItem` настраиваемым? Например, добавить метод `setLayout()`, в который передается id layout-ресурса, в котором должен быть TextView с id ymk_balloon_text_view.
