### ISSUE TITLE
SetNightMode(true) error

### ISSUE THREAD

**Issue by denmusic1992** [yandexmobile/yandexmapkit-android#206]
Доброго времени суток. Мое приложение должно поддерживать две темы. При включении темной темы я пытаюсь вызвать метод у mapController'а setNightMode. В ответ получаю ошибку со следующими логами:
`No implementation found for void ru.yandex.yandexmapkit.utils.Utils.InvertBitmapNative(short[], int) (tried Java_ru_yandex_yandexmapkit_utils_Utils_InvertBitmapNative and Java_ru_yandex_yandexmapkit_utils_Utils_InvertBitmapNative___3SI)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime: FATAL EXCEPTION: main
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime: Process: com.development.aisisso.isso_r, PID: 5594
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void ru.yandex.yandexmapkit.utils.Utils.InvertBitmapNative(short[], int) (tried Java_ru_yandex_yandexmapkit_utils_Utils_InvertBitmapNative and Java_ru_yandex_yandexmapkit_utils_Utils_InvertBitmapNative___3SI)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime:     at ru.yandex.yandexmapkit.utils.Utils.InvertBitmapNative(Native Method)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime:     at ru.yandex.yandexmapkit.utils.Utils.a(Unknown Source)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime:     at ax.b(Unknown Source)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime:     at ax.c(Unknown Source)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime:     at ru.yandex.yandexmapkit.MapModel.setNightMap(Unknown Source)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime:     at ru.yandex.yandexmapkit.MapModel.setNightMode(Unknown Source)
03-15 17:24:48.298 5594-5594/com.development.aisisso.isso_r E/AndroidRuntime:     at ru.yandex.yandexmapkit.MapController.setNightMode(Unknown Source) 
...............................`
В чем может быть проблема?

**Comment by mksaint13** [comment]
Напишите  на какой  версии вы собираете  и  на каком андройде  трестируете. Так  же используется  ли обфускатор.

**Comment by shwalabaka** [comment]
версия yandex:yandexmapkit:2.4.0, Android 5.1.1 , обфускатор не использую. Выдает ту же ошибку

**Comment by mksaint13** [comment]
Спасибо за фидбек. В ближайшее время исправим.

**Comment by denmusic1992** [comment]
> версия yandex:yandexmapkit:2.4.0, Android 5.1.1 , обфускатор не использую. Выдает ту же ошибку
У меня такие же параметры. Также на некоторых телефонах (sony xperia z1 compact в частности) при инициализации карты устройство начинает зависать..

**Comment by mksaint13** [comment]
Ошибку исправили.

**Comment by shwalabaka** [comment]
спасибо большое, все работает
