### ISSUE TITLE
Как подключить YMK к Android Studio?

### ISSUE THREAD

**Issue by AleVerDes** [yandexmobile/yandexmapkit-android#208]
Как подключить YMK к Android Studio?
Есть ли у кого-нибудь примитивный проект с подключенным YMK и гарантировано работающий с вашим apiKey? Цель всей этой эпопеи — проверить выданный apiKey на момент работы, т.к. в проекте на Xamarine карты не подгружается и нужно понять, это проблема Xamarina или Yandex'а. Для этого как раз нужно проверить ключ на официальных примерах. Потому и прошу minimal-проект с картами.

**Comment by mksaint13** [comment]
В ближайшее время добавим.

**Comment by mksaint13** [comment]
Добавил  в yandexmapkit-sample сборку через gradle.  Теперь  можешь собирать и проверять.
