### ISSUE TITLE
Didn't find class "cq" on path

### ISSUE THREAD

**Issue by alarmtrade** [yandexmobile/yandexmapkit-android#211]
После обфускации падает
Caused by: java.lang.ClassNotFoundException: Didn't find class "cq" on path: DexPathList

**Comment by mksaint13** [comment]
Добавте  -keep class ru.yandex.yandexmapkit.** { *; }

В дальнейшем мы  всенес  это в  библиотеку по умолчанию.

**Comment by alarmtrade** [comment]
не помогает
в обфусцированном apk отсуствует класс cq котрый находиться в defpackage
если отключить proguard то все нормально данный класс присутствует
