### ISSUE TITLE
Как вывести карту и марке для определения адреса? 

### ISSUE THREAD

**Issue by Deno95** [yandexmobile/yandexmapkit-android#212]
Привет всем. Не давно начал работать с android, нужна помощь знающих разработчиков. Делать проект буду на android studio. Нужна реализовать что то подобное http://s06.radikal.ru/i179/1604/a2/42cf797383b5.png

Надо вывести отображения карты нужного города _(я так понимаю тут можно задать координаты)_ и маркер в центре экрана. Когда буду двигать карту и наведу нужный объекта на маркер мне надо вывести адрес этого объекта. 

**p.s** Подскажите как это лучше реализовать. Может есть примеры на эту тему или еще что. Хотелось бы знать, нормально ли эта библиотека ставиться на android studio?

**Comment by mksaint13** [comment]
Посмотрите пример 
https://github.com/yandexmobile/yandexmapkit-android/blob/master/yandexmapkit-sample/src/ru/mapkittest/geocode/OverlayGeoCode.java
