### ISSUE TITLE
Didn't find class "cq" on path

### ISSUE THREAD

**Issue by alarmtrade** [yandexmobile/yandexmapkit-android#214]
После обфускации падает
Caused by: java.lang.ClassNotFoundException: Didn't find class "cq" on path: DexPathList

-keep class ru.yandex.yandexmapkit.** { *; }

не помогает
в обфусцированном apk отсуствует класс cq котрый находиться в defpackage
если отключить proguard то все нормально данный класс присутствует

**Comment by mksaint13** [comment]
В ближаешее вермя выпустим обновленную версию.  Подождите немного.

**Comment by alarmtrade** [comment]
спасибо ... ждем

**Comment by mksaint13** [comment]
Добавили конфигурацию,  пробуйте.

**Comment by alarmtrade** [comment]
все отлично в версии 2.4.2 работает
