### ISSUE TITLE
Yandex map

### ISSUE THREAD

**Issue by Deno95** [yandexmobile/yandexmapkit-android#215]
Может, кто знает как реализовать yandex map на android, чтобы она работала быстро и без лагов? Пробовал использовать yandex mapkit библиотеку, но что-то там не все гладко работает, затем пробовал через API, и выводить в WebView, но снова есть проблемы. Как-то это все не то, либо я плохо реализовал.

Хочу добиться такого же результата, как в этом приложении: https://play.google.com/store/apps/details?id=ru.taximaster.tmtaxicaller.id0960&hl=ru

Может, кто знает, как там реализована карта yandex?

p.s Есть подозрения что  приложения использует карту osm и накладывает на ней тайлы yandex map

**Comment by lassana** [comment]
Судя по скринам, там мапкит.

https://lh3.googleusercontent.com/9Hwt4Gxb7LQBP_2X-Amj3EdpGITAtdSsVrXvzq6uaDOiHz7MbVmHVGNTCk3oV_quUv8=h900

https://github.com/yandexmobile/yandexmapkit-android/blob/master/yandexmapkit-library/res/drawable-xhdpi/ymk_zoom_plus.png

**Comment by Deno95** [comment]
@lassana  когда ты ей пользуешься там не чувствуется что это mapkit) Там вроде как была взята osm и на неё перенесена yandex карта по средством тайлов. Это вообще реально и на сколько практично?

**Comment by lassana** [comment]
>osm

Имеете ввиду osmdroid? Да, реально, т.к. тайлы от Яндекс есть картинки. Вот [тут](https://habrahabr.ru/post/151103/) описана идея, но я не уверен, что такие действия удовлетворяют лицензии Яндекс карт.

Мб яндексовые тайлы можно отображать и через GoogleMapsV2 через свой TileProvider.

**Comment by Deno95** [comment]
@lassana  чем грозит нарушения пользовательского соглашения?

**Comment by mksaint13** [comment]
Попробуйте указать в  xml  для mapView  параметр android:tag="static"

Это  позволит использовать стандартную отрисовку во View  и дальше применится  оптимизация  самого андройда.  Посмотрите  по  скорости  устраивает ли вас отрисовки карты в приложении https://play.google.com/store/apps/details?id=com.edadeal.android

**Comment by Deno95** [comment]
@mksaint13  Добавил строчку android:tag="static" и это дало совсем другой результат. Спасибо большое. 

Может вы знаете еще как на прямую получить названия улицы и номер дома зная координаты? 

По этому примеру я могу получить при каком нибудь действии адрес https://github.com/yandexmobile/yandexmapkit-android/blob/master/yandexmapkit-sample/src/ru/mapkittest/geocode/OverlayGeoCode.java

Я хочу напрямую передать туда координаты и получить адрес (как это правильно сделать?).
Сейчас я это делаю в обход библиотеке а хотелось бы это делать через неё.

**Comment by mksaint13** [comment]
getMapController().getDownloader().getGeoCode(new GeoCodeListener {....}, getMapController().getGeoPoint(КООРДИНАТЫ));

Вот.

**Comment by Deno95** [comment]
@mksaint13 Как то так?

```
GeoPoint geoponit = new GeoPoint(50, 50);

mapView.getMapController().getDownloader().getGeoCode(new GeoCodeListener() {
    @Override
        public boolean onFinishGeoCode(GeoCode geoCode) {
                        return false;
        }
}, geoponit);
```

Если так, то что то у меня не получается вывести адрес. В onFinishGeoCode наверное что то с потоком надо делать.
