### ISSUE TITLE
GeoCode

### ISSUE THREAD

**Issue by DenoBY** [yandexmobile/yandexmapkit-android#216]
Что я не так делаю? Пытаюсь получить адрес напрямую, geoCode пустой. 

```
GeoPoint geoponit = new GeoPoint(50, 50);

mapView.getMapController().getDownloader().getGeoCode(new GeoCodeListener() {
    @Override
        public boolean onFinishGeoCode(GeoCode geoCode) {
            Log.e("geoCode", ""+geoCode);
            return false;
        }
}, geoponit);
```

**Comment by mksaint13** [comment]
Вы  это делаете  в  onCreate ?

**Comment by Deno95** [comment]
@mksaint13  да

**Comment by mksaint13** [comment]
Ясно.  Дело в том что мапкит   а данный  фрейм  еще  не полностью проинициализировался. По  этому  могу  предложить перенести  в  дргой  метод,  например  на  клик,  или  положить его  в  выполнение в  post
