### ISSUE TITLE
Fatal signal 11 (SIGSEGV), thread 28848 (ymm-main)

### ISSUE THREAD

**Issue by PetrBe** [yandexmobile/yandexmapkit-android#218]
Проблема из тикета #203 . Там написано что ошибка исправлена в новой версии. Обновились - проблема осталась. ADB логи прикладываю.
[mapkit_crash.txt](https://github.com/yandexmobile/yandexmapkit-android/files/306959/mapkit_crash.txt)

**Comment by mksaint13** [comment]
День добрый  можете написать, на каком устройстве трестируете. Так же если не затруднить написать тестовое приложение и описать шаги воспроизведения бага.

**Comment by PetrBe** [comment]
Добрый день!
Проверялось на устройствах:
Samsung galaxy tab 4 sm-t231, Android 4.4.2
LG K8 LTE, Android 6.0 
x86 эмулятор, который в комплекте с SDK
ADB логи эмклятора - [mapkit_crash2.txt](https://github.com/yandexmobile/yandexmapkit-android/files/313818/mapkit_crash2.txt)
SYSTEM_TOMBSTONE (упоминается в этих логах) - 
[tombstone_01.txt](https://github.com/yandexmobile/yandexmapkit-android/files/313820/tombstone_01.txt)
Приложение - yandexmapkit-sample из этого репозитария. Воспроизводить просто - запустить приложение, и скроллировать карту, иногда падает сразу, иногда несколько минут поскроллиоровать.

**Comment by mksaint13** [comment]
Спасибо будем пробывать воспроизвести

**Comment by PetrBe** [comment]
Да, на этих точно воспроизводится, спасибо очень будем ждать исправления.

**Comment by saint13** [comment]
Вы мне можете прислать адрес. Я вам вышлю тестовую версию. Так вы сможете проверить на своих девайсах.
Пишите на mksaint13@yandex-team.ru

**Comment by PetrBe** [comment]
добрый день! Есть какие-либо результаты по данному тикету? Спасибо!

**Comment by saint13** [comment]
Привет.

Как  писал ранее.  Проблема пока не решил.

Если окунутся в детали.  То  получается  андройд  нежится при  работе с
картонкой.  Данная картинка  100%   валидна.  Обработка всех исключений
пока не помогла.  Вот какие  дела.  Есть предложение протащить все через
 JNI,  но  это попробуем  попозже.

4 июля 2016 г., 15:43 пользователь PetrBe <notifications@github.com>
написал:

**Comment by saint13** [comment]
Привет выложили версию, которую вы проверяли на стабильность.  Плюс отказались от всех ненужных пермишен.

**Comment by PetrBe** [comment]
спасибо!!

2016-07-20 20:31 GMT+04:00 saint13 <notifications@github.com>:

**Comment by khrameev** [comment]
аналогичная проблема появилась и на новой версии на устройствах
Galaxy Tab S2 9.7 (gts210lte)
Galaxy S7 (herolte)

**Comment by saint13** [comment]
Хорошо проверим.

23 окт. 2016 г. 12:04 PM пользователь "khrameev" <notifications@github.com>
написал:
