### ISSUE TITLE
How to get location information in Turkish or English not Russian

### ISSUE THREAD

**Issue by AlicanAkyol** [yandexmobile/yandexmapkit-android#222]
Hello,
I want to use yandex map api in my android app but address is shown in russian. So it doesnt provide for me. Can I get data in turkish? How?

Other Question
How does it show path for one point to another point?

Thanks.

**Comment by saint13** [comment]
Hello.  Address is shown in russian on map?

How does it show path for one point to another point?
Mapkit not have service route, but  you  draw your route. See sample

2016-09-01 11:56 GMT+03:00 AlicanAkyol <notifications@github.com>:
