### ISSUE TITLE
Отсутствуют кнопки на карте

### ISSUE THREAD

**Issue by neyron91** [yandexmobile/yandexmapkit-android#224]
Пытаюсь на карте отобразить компоненты:
```
map.showJamsButton(true);
map.showScaleView(true);
map.showFindMeButton(true);
map.showZoomButtons(true);
map.showBuiltInScreenButtons(true);
```
Но из них на карте появляется только "масштабирование" и "мое расположение".
Использую последнюю версию библиотеки. В build.gradle:
```
maven { url 'https://github.com/yandexmobile/yandexmapkit-android/raw/maven/' }
compile 'ru.yandex:yandexmapkit:2.5.0@aar'
```

Это ошибка или в 2.5.0 что-то поменялось?

**Comment by saint13** [comment]
Привет, можешь  прислать тестовые приложение на mksaint13@yandex-team.ru

**Comment by neyron91** [comment]
По почте отправил письмо, но к сожалению с вложением не смог отправить, прикрепляю тут:
[YandexTest.zip](https://github.com/yandexmobile/yandexmapkit-android/files/513286/YandexTest.zip)

**Comment by saint13** [comment]
Спасибо посмотрю в ближайшее время.

**Comment by saint13** [comment]
Исравлено,  так же  есть возможность самим создавать контролы на карте.
