### ISSUE TITLE
не определяет местоположение на Android 6.0 

### ISSUE THREAD

**Issue by yuriChechetkin** [yandexmobile/yandexmapkit-android#225]
На новых версиях Android os не определяет местоположение

**Comment by saint13** [comment]
Необходимо самому запрашивать разрешение на локацию.

**Comment by yuriChechetkin** [comment]
начиная с какой версии и где можно посмотреть пример? метод
mapController.getOverlayManager().getMyLocation().getMyLocationItem().getGeoPoint();
нужно обернуть во что-то?

**Comment by saint13** [comment]
Попробуем в ближайшее время доделать пример, а так 
https://developer.android.com/training/permissions/requesting.html 

 Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION

**Comment by yuriChechetkin** [comment]
спасибо, было бы здорово

**Comment by saint13** [comment]
Работа с премишинами добавлен в пример.
