### ISSUE TITLE
Цвета и фона, и текста balloon белые, так что текст не видно.

### ISSUE THREAD

**Issue by mxl** [yandexmobile/yandexmapkit-android#226]
Проверял на Android 4.4.4

**Comment by saint13** [comment]
Вы можете сделать полностью  кастомный балун. Для этого необходимо написать
свой xml. Можете посмотреть в примере.

11 окт. 2016 г. 22:19 пользователь "Michael Ledin" <notifications@github.com>
написал:

**Comment by mxl** [comment]
Я попробую, но, наверное, хорошо бы было, если бы все из коробки работало.

**Comment by saint13** [comment]
Мапкита дает возможность в балун запихнуть почти любой лейаут. Все зависит
от задач. Можете посмотреть приложение edadeal.

11 окт. 2016 г. 22:48 пользователь "Michael Ledin" <notifications@github.com>
написал:

**Comment by saint13** [comment]
Если Вам необходима помощь с  реализацией, то пишите.

**Comment by mxl** [comment]
@saint13 Спасибо, я разобрался.
