### ISSUE TITLE
Кэширование

### ISSUE THREAD

**Issue by whitegrade** [yandexmobile/yandexmapkit-android#227]
Подскажите что с кэшированием карт? Подключил к Android Studio, подвигал туда-сюда и карты загружаются по-новой, словно его нет

**Comment by saint13** [comment]
Кеширование есть. Можете проверить на реальном устройстве с выключением
интернета?

2 нояб. 2016 г. 5:16 PM пользователь "whitegrade" <notifications@github.com>
написал:

**Comment by whitegrade** [comment]
Не совсем точно выразился. Пример: после загрузки приложения карты местности (например, Москвы), загружаются из интернета. Перемещаемся в Питер, возвращаемся в Москву - карты Москвы загружаются снова из интернета. Выключаем приложение, включаем - снова нужен интернет для загрузки карт Москвы.

**Comment by saint13** [comment]
В связи с тем что тайлы растровые. То мы ограничили кеш. По метрикам было
видно, что если пользователь находится в одной локации то этого кеша ему
будет достаточно. Иначе если пользователь установит много приложений с
мапкитом у него быстро закончится память на устройстве.

3 нояб. 2016 г. 1:03 PM пользователь "whitegrade" <notifications@github.com>
написал:

**Comment by whitegrade** [comment]
Спасибо за поддержку
