### ISSUE TITLE
DragAndDropItem перемещение

### ISSUE THREAD

**Issue by NoNews** [yandexmobile/yandexmapkit-android#231]
Можно ли сделать так, чтобы при перелистывании карты DragAndDropItem стоял на одном месте, а карта перемещалась слоем ниже? (т.е. DragAndDropItem не пропадает с экрана, а при перелистывании просто накладывается поверх карты, где можно получить текущие координаты)

**Comment by NoNews** [comment]
@mksaint13 Будет ли ответ? Этот вопрос очень важен. Мы вынуждены в некоторых приложениях использовать именно ymk.

**Comment by saint13** [comment]
А Вам  DragAndDropItem точно нужем? 
Если да,  то можно  отнаследоваться  от  него и  повесить событие на  скролл,  и  менять  положение  Item  при сброле карты.  

Если нет,  то  можно добавить  поверх карты View  c ресурсом.  

Так же более  подробно смогу помочь если будет больше данных или какой  пример как  должно быть.

**Comment by NoNews** [comment]
@saint13  Если просто сделать вьюху, то смутно представляю, как определить lat/lon/address по расположению именно этой вьюхи)
Пример - яндекс такси. Мы заходим в приложение, и можем двигать карту, при этом маркет текущего местоположения не пропадает из видимости + если его остановить - он определит адрес.


При создании использую вот этот код(пока что чисто DragAndDrop получается):

```
    private void setupMap() {
        mapView.showFindMeButton(true);
        mapView.showJamsButton(false);
        mapView.showScaleView(false);
        mapController = mapView.getMapController();
        mapController.setZoomCurrent(17);
        mapController.zoomIn(17,17);
        mapController.setPositionNoAnimationTo(currentUserGeoPoint);
        overlayManager = mapController.getOverlayManager();
        overlayManager.getMyLocation().setEnabled(true);
        overlayManager.getMyLocation().setAutoScroll(true);
        overlayManager.getMyLocation().setVisible(false);
        overlay = new DragAndDropOverlay(mapController);
    }

    private void showMarker() {
        DragAndDropItem drag1Item = new DragAndDropItem(currentUserGeoPoint, getContext().getDrawable(R.drawable.map_marker));
        drag1Item.setDragable(true);
        drag1Item.setOffsetX(mapSelectPresenter.getOffsetX());
        drag1Item.setOffsetY(mapSelectPresenter.getOffsetY());
        BalloonItem balloonDrag = new BalloonItem(getContext(),drag1Item.getGeoPoint());
        balloonDrag.setText("Точка приезда такси");//// FIXME: 23.11.2016 
        balloonDrag.setOffsetX(mapSelectPresenter.getOffsetX());
        drag1Item.setBalloonItem(balloonDrag);
        overlay.addOverlayItem(drag1Item);
        overlayManager.addOverlay(overlay);
    }

```

**Comment by saint13** [comment]
Если смотреть  как  в  я.такси. То тут все просто можно реализовать.  Положить  вью под центру над картой.  Далее  отслеживать сколл/зум/скале, и как только  остановилась,  то перевести экранные координаты в  гео, далее гео координаты  перевести в адрес.

**Comment by NoNews** [comment]
хм...получается, тогда нужно центрировать карту при старте,+ определять адрес именно с getMapCenter.
Попробую, отпишусь о результатах. Не закрывайте пока что обращение.
Спасибо!

**Comment by NoNews** [comment]
Работает хорошо.
