### ISSUE TITLE
mkdir failed: ENOENT (No such file or directory) : /storage/emulated/0/yandexmaps/data/cache/ru-RU/200/config

### ISSUE THREAD

**Issue by IvanKorol87** [yandexmobile/yandexmapkit-android#234]
Проблема в новых версиях андроид...Если поправите сразу целый комплекс аномальных ошибок пропадет...Очень ждем...спасибо

**Comment by saint13** [comment]
Спасибо, будем смотреть.  Можете  более  точные шаги где, на чем и как  воспроизводится.

**Comment by IvanKorol87** [comment]
При первой загрузке карт...Да и вообще уже интегрирую 2ой день...нашел
около 10ка серьезных глюков...
Вот например самый страшный...карта не подгружается просто сетка на белом
фоне...как только начинаешь зумить пальцами...что то прорисовывается...и
вот так нужно ловить масштаб, в котором карту видно...если отключить HD
режим...карта не пропадает...но через некоторое время просто крешет
приложение...

Проверка на Samsung s6, s7 Android 6.
Если Вы знаете как исправить этот баг...прошу сообщите...

2016-11-27 14:36 GMT+03:00 saint13 <notifications@github.com>:

**Comment by IvanKorol87** [comment]
После 5 дней А...боли с картами пишу свои краткие рекомендации.
Большинство проблем связанных с прорисовкой у меня было вызвано созданием карт, динамически через код. 
1. Нужно создавать почему-то только через XML с тегом Static.
<ru.yandex.yandexmapkit.MapView
                android:id="@+id/yandex_map"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:tag="static"
                android:apiKey="ключ чистым текстом без ссылки на ресурс"/>

 2. Ключ обязательно нужно прописывать статически, а не через getStrings.

Уважаемые господа из Яндекса, очень большая просьба к Вам...после динамического создания через код и с использованием Weak ссылок...после поворота телефона приложение падает.
Насколько я понимаю это из за утечки памяти в библиотеке (Прилагаю скрины) В связи с отсутствием нормально документации, очень прошу Вас подскажите как можно закрыть это соединение? 
![leakyandex](https://cloud.githubusercontent.com/assets/22576468/20858555/20ae9c18-b958-11e6-998e-da5cbb499a85.png)
![leakyandex2](https://cloud.githubusercontent.com/assets/22576468/20858556/20b34a42-b958-11e6-9bb8-82c6e9d19129.png)
![leakyandex3](https://cloud.githubusercontent.com/assets/22576468/20858557/20b5885c-b958-11e6-9c05-b9693b7500e9.png)

**Comment by saint13** [comment]
Спасибо будем смотреть.


3 дек. 2016 г. 12:58 PM пользователь "IvanKorol87" <notifications@github.com>
написал:
