### ISSUE TITLE
Отствует возможность понять причину эвента:апи или действие пользователя

### ISSUE THREAD

**Issue by punksta** [yandexmobile/yandexmapkit-android#237]
В документации `ru.yandex.yandexmapkit.map.OnMapListener` написанно, что эвенты - следствие взаимодействия пользователя с картой. Но если вызвать ```setPositionAnimationTo```, то в листенер тоже получит путь изменения карты. Приходится писать велосипеды, которые некогда писали для [google maps](http://stackoverflow.com/questions/13702117/how-can-i-handle-map-move-end-using-google-maps-for-android-v2). Было бы неплохо добавить информацию о причине события: действия пользователя или вызов одного из апи. Вот как [это](https://developers.google.com/maps/documentation/android-api/events#camera-change-events) реализовано в гугл картах. 
Спасибо

**Comment by saint13** [comment]
Спасибо, за  фидбек.  Попробуем добавить  в АПИ

**Comment by saint13** [comment]
Проверяйте

**Comment by nicfedor** [comment]
Есть ли возможность передать из своего приложения в навигатор маршрут с несколькими промежуточными точками? Или только начальную и конечную точку маршрута?

**Comment by punksta** [comment]
@saint13 isGesture не возращает true для SCALE методов от жестов зума двумя пальцами

**Comment by saint13** [comment]
Спасибо посмотрю.

7 февр. 2017 г. 19:36 пользователь "Stanislav Shakirov" <
notifications@github.com> написал:

**Comment by punksta** [comment]
@saint13 нет никаких новостей?

**Comment by saint13** [comment]
Вечер добрый прошу еще немного подождать, все на подходе.

2017-02-27 19:22 GMT+03:00 Stanislav Shakirov <notifications@github.com>:
