### ISSUE TITLE
Показать значок текущее местоположение

### ISSUE THREAD

**Issue by AlexSpirin1990** [yandexmobile/yandexmapkit-android#238]
При открытии приложения долго появляется значок с текущим местоположением, бывает по 18 секунд. А если нажать на кнопку найти меня, то сразу же появится. Какой метод вызывается по нажатию на кнопку найти меня ? Или что можно сделать для появления значка с текущим местоположением сразу после открытия карты ?

**Comment by alinaSibiryakova** [comment]
@AlexSpirin1990 
Приветствую! У меня аналогичный вопрос к разработчикам YMK. 
Пока нашла для себя такое решение: https://developer.android.com/training/location/receive-location-updates.html#get-last-location.

**Comment by saint13** [comment]
День добрый извините что долго не отвечал.  Сейчас занимаемся данной проблемой.

**Comment by saint13** [comment]
Замена нажатие на  кнопку overlayManager.getMyLocation().findMe();

**Comment by alinaSibiryakova** [comment]
Спасибо за ответ! Есть еще такой вопрос. Существует ли в ymk метод позволяющий установить zoom на таком уровне, чтобы  на экран уместилась определенная группа точек (bounds)?2:43, 18 декабря 2016 г., saint13 <notifications@github.com>:Замена нажатие на  кнопку overlayManager.getMyLocation().findMe();—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.    -- Отправлено из мобильного приложения Яндекс.Почты

**Comment by saint13** [comment]
Да есть посмотрите в примере

19 дек. 2016 г. 18:17 пользователь "alinaSibiryakova" <
notifications@github.com> написал:

**Comment by NoNews** [comment]
@saint13  `overlayManager.getMyLocation().findMe();` так же срабатывает очень редко при старте(
Как обстоят дела с данным вопросом?

**Comment by saint13** [comment]
Давайте я опишу логику работы определения местоположения.  
1. Сначала идет проверка вашего ключа что  он валиден.
2. Далее запускается GPS и запускается  сервис Yandex LBS.  

На этом все.  

Если есть возможность сделать тестовое  приложение где 100% повторяется на разных девайсах,  то возможно мы нашли узкое звено.  На данный момент  на тестовых девайсах на которы я прогонял библиотеку, все запросы в Yandex LBS уходят и gps  поднимается.

**Comment by NoNews** [comment]
@saint13  Или может какой-нибудь каллбэк сделать, на подобии `onMapReady`, для этой ситуации?

Запускаю данный метод хандлером, с задержкой в 4 секунды. всё равно иногда местоположение не определяется.
`new Handler().postDelayed(() -> overlayManager.getMyLocation().findMe(), 3000);`

Протестирую в отдельном проекте на разных устройствах, сообщу о результатах
