### ISSUE TITLE
Кастомизация балуна

### ISSUE THREAD

**Issue by punksta** [yandexmobile/yandexmapkit-android#241]
Добрый вечер. Столкнулся с проблемой при реализации балуна. Задача: свой лейаут для балуна и отсутствие стрелки(указателя) снизу.
Лейаут выглядит так.
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.ctrlplusz.anytextview.AnyTextView
        android:id="@+id/ymk_balloon_text_view"
        style="@style/BalloonButton"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:paddingBottom="2dp"
        android:paddingLeft="20dp"
        android:paddingRight="20dp"
        android:paddingTop="2dp"
        android:text="Ип блаблабла"
        android:textSize="15sp" />
</LinearLayout>
```
Применение лейаута
```
public class MarkerBallonoItem extends BalloonItem {
    final StoreMarker marker;
    final OverlayItem item;
    boolean active = false;

    public MarkerBallonoItem(Context context, GeoPoint geoPoint, @NonNull StoreMarker marker, OverlayItem item) {
        super(context, geoPoint);
        setText(marker.getName());
        this.marker = marker;
        this.item = item;
    }

    @Override
    public void inflateView(Context context) {
        this.model = (ViewGroup) LayoutInflater.from(context).inflate(R.layout.item_marker_balloc, null);
        this.j = (TextView) model.findViewById(R.id.ymk_balloon_text_view);
    }
}
Так убираю стрелку. Из метода `a` удалена часть с рисованием ymk_balloon_tail_black 
```
class StoreBalloonRender extends BalloonRender {

    StoreBalloonRender(Context context) {
        super(context);
    }

    @Override
    public void a(Canvas var1, BalloonItem var2) {
        Bitmap var3;
        if((var3 = var2.f()) != null && !var3.isRecycled()) {
            ScreenPoint var4 = var2.getScreenPoint();
            int var5 = var2.getOffsetX() - var2.getOffsetCenterX();
            int var6 = var2.getOffsetY() - var2.getOffsetCenterY();
            RectF var7 = new RectF(var4.getX() + (float)var5 - (float)var2.e() * var2.p / 100.0F, var4.getY() - (float)this.b + (float)var6 - (float)var3.getHeight() * var2.p / 100.0F, var4.getX() + (float)var5 + (float)(var3.getWidth() - var2.e()) * var2.p / 100.0F, (float)(Math.round(var4.getY()) - this.b + var6));
            Rect var10 = new Rect(0, 0, var3.getWidth(), var3.getHeight());
            var1.drawBitmap(var3, var10, var7, null);
        }
    }
}

```

Проблема: TextView балуна с одним словом(без пробелов) разбиваются на 3 строки строки, по несколько символов в одной строке.

**Comment by saint13** [comment]
А можешь прислать макет как  должно быть.
Так как BalloonRender не надо делать.  Все что нужно это  сверстать правильно xml. 

Как пример  сложного https://play.google.com/store/apps/details?id=com.edadeal.android
Можешь перейти на карту  и посмотреть.

**Comment by saint13** [comment]
Если вам нужно отображать что то своим шрифтом то можно использовать uk.co.chrisjenx:calligraphy

**Comment by punksta** [comment]
Какой-бы я layout не сверстал, стандартный BallonOverlay будет рисовать стрелку под ним. Писать свой BallonOverlay не очень хочется, учитывая постановку задачу.

**Comment by punksta** [comment]
[![ballon.png](https://s27.postimg.org/ifdmckfc3/ballon.png)](https://postimg.org/image/4ygntp50f/)
Вот пример макета. Если название из одного слова(без пробелов), балус у textview будет 3 строки.

**Comment by saint13** [comment]
Стрелка это ресурс который вы можете заменить  своим  прозрачным.

**Comment by punksta** [comment]
Признаться, не представляю, как это возможно без переупаковки .arr файла.
Если бы вы написали инструкцию...
На сколько мне известно все ресурсы жестко привязанны к id из R файла.
```
package ru.yandex.yandexmapkit;

public final class R {
	public static final class drawable {
		public static final int ymk_balloon_black = 0x7f0200dc;
		public static final int ymk_balloon_tail_black = 0x7f0200dd;
```
А при поиске по имени учитывается текущий пакет, дабы избежать конфликтов именования.

**Comment by saint13** [comment]
На сколько мне известно. Вы можете создать в своем проекте ymk_balloon_tail_black  и данный ресурс будет приоритетный.

**Comment by saint13** [comment]
Так многие делают для изменения  балуна и иконки местоположения.
