### ISSUE TITLE
MemoryLeak

### ISSUE THREAD

**Issue by isaevKonstantin** [yandexmobile/yandexmapkit-android#243]
Всем привет.При работе с YandexMapKit есть утечки памяти(держит ссылку на Activity).Как сделать destroy или подобный метод,чтобы очистить ссылки на activity? Update: Скачал ваш sample, также всюду утечки.

**Comment by orwir** [comment]
Дополню проблему:

* package.MyActivity has leaked:
* GC ROOT static ru.yandex.yandexmapkit.MapController.fileCache
* references ru.yandex.am.F
* leaks package.MyActivity instance
* Retaining: 270 КБ.
* Reference Key: 61e27181-c04d-4057-9939-cf4991762fdb
* Device: Xiaomi Xiaomi Redmi 3S land
* Android Version: 6.0.1 API: 23 LeakCanary: 1.5 00f37f5
* Durations: watch=5603ms, gc=165ms, heap dump=3616ms, analysis=52967ms

**Comment by isaevKonstantin** [comment]
Да этот leak .Напишите пожалуйста,если сможете решить.У меня пока результата нет,к сожалению(

**Comment by saint13** [comment]
Спасибо посмотрим в ближайшее время

**Comment by saint13** [comment]
Сделали фикс в  ближайшее время выкатим.

**Comment by saint13** [comment]
Исправил проверяйте.

**Comment by isaevKonstantin** [comment]
Проверил на вашем sample.Все activity по которым я перехожу отмечены как leaked.

**Comment by saint13** [comment]
Спасибо,  сейчас  посмотрим.

2016-12-26 12:01 GMT+03:00 isaevKonstantin <notifications@github.com>:

**Comment by saint13** [comment]
Обновил библиотеку.  Вроде  все утечки в библиотеке устранил,  если что еще будте  пишите.  Так не забудьте  обновить зависимости.
