### ISSUE TITLE
Маршрут

### ISSUE THREAD

**Issue by NoNews** [yandexmobile/yandexmapkit-android#246]
Здравствуйте.
Постройка маршрута возможна?
Пробовал через вот этот пример:

https://github.com/yandexmobile/yandexmapkit-android/tree/master/yandexmapkit-sample/src/ru/mapkittest/path

Но путь не отображается, +, если расстояние очень большое - получаю ошибку 
`Path too large to be rendered into a texture`

**Comment by saint13** [comment]
Возможности нет. А так надо что то думать самому.

22 дек. 2016 г. 21:14 пользователь "Alex Bykov" <notifications@github.com>
написал:
