### ISSUE TITLE
Метки попадают на балун

### ISSUE THREAD

**Issue by AlexSpirin1990** [yandexmobile/yandexmapkit-android#247]
Когда нажимаю на метку, на балуне этой метки появляются другие метки. Как сделать, чтобы балун всегда был поверх меток ?
![screenshot_20161223-164318](https://cloud.githubusercontent.com/assets/22980081/21455323/6c23b47a-c930-11e6-8dde-18ecc87d44ac.png)

**Comment by saint13** [comment]
Здесь все просто. Укажите нужный приоритет у ваших items setPriority ниже чем у BallounItem,  сейчас они имеют  одинаковый приоритет и  поэтому сортируются по Z-index
