### ISSUE TITLE
Несколько балунов в Яндекс Навигаторе

### ISSUE THREAD

**Issue by Mezmeraiz** [yandexmobile/yandexmapkit-android#248]
Можно ли в Яндекс навигаторе установить сразу несколько балунов? Посылаю интент из приложения c ru.yandex.yandexnavi.action.SHOW_POINT_ON_MAP. В навигаторе ставится балун, но при повторном интенте с другими координатами старый балун пропадает и заменяется на новый.

**Comment by saint13** [comment]
Нет не возможно.

25 дек. 2016 г. 21:15 пользователь "Mezmeraiz" <notifications@github.com>
написал:
