### ISSUE TITLE
Изменение дефолтной иконки MyLocationItem

### ISSUE THREAD

**Issue by Nook2007** [yandexmobile/yandexmapkit-android#255]
Здравствуйте. Пытаюсь изменить иконку, но она остается прежней, ЧЯДНТ?
```    @Override
    public void onMyLocationChange(MyLocationItem myLocationItem) {
        myLocationItem.setDrawable(ContextCompat.getDrawable(this, R.drawable.yandex2));
    }
```

**Comment by saint13** [comment]
Для этого вам не надо ничего править в коде. Достаточно подложить свой
ресурс с именем ресурса из библиотеки.

17 февр. 2017 г. 19:31 пользователь "Nook2007" <notifications@github.com>
написал:

**Comment by Nook2007** [comment]
А если мне нужно в рантайме менять ее?

**Comment by saint13** [comment]
Тогда легче написать свой слой и подписаться на события местоположения.

17 февр. 2017 г. 19:35 пользователь "Nook2007" <notifications@github.com>
написал:

**Comment by Nook2007** [comment]
Спасибо
