### ISSUE TITLE
Клик по маркеру

### ISSUE THREAD

**Issue by ArtyomV96** [yandexmobile/yandexmapkit-android#256]
Нужно отловить клик по маркеру и выполнить действие. Но на данный момент такого метода нет, возможно ли это сделать как-то другим способом?

**Comment by bartwell** [comment]
Есть метод `MapPolygonsCollection.addTapListener()`.

**Comment by saint13** [comment]
Можно создать свой Overlay и  смотреть onSingleTapUp, в новой версии  будет доступен метод.  onSearchItem, который будет возвращать  макер. Если этот маклер находится по координатам x,y  из  метода onSingleTapUp

**Comment by saint13** [comment]
Или попробуем успеть добавить колбек клика на  марке.  Это будет разумней
