### ISSUE TITLE
Карта рисуется поверх фрагментов

### ISSUE THREAD

**Issue by CoolMind** [yandexmobile/yandexmapkit-android#259]
Здравствуйте!
При работе с YMK возникает ряд проблем отображения карты. Использую активность с фрагментами и боковым меню (Navigation drawer).
1. Иногда заметно, что карта рисуется поверх других фрагментов, если они сами используют SurfaceView (выводят содержимое камеры).
2. На одном устройстве (Philips) при вызове бокового меню карта рисуется поверх бокового меню.
3. Если в одном фрагменте рисовалась карта, затем открыли другой фрагмент и там отобразили другую карту, то происходит следующее. Пусть в первом фрагменте был Нск, а во втором - Москва, тогда во весь экран будет нарисован Нск вместо Москвы, при этом карта будет полностью неподвижна, кнопки приближения не работают, balloon'ы - тоже. Вернувшись обратно в первый фрагмент, снова увидим Нск, при этом всё работает.
Теперь если в XML-разметке уменьшить размеры карты для первого фрагмента, то во втором фрагменте увидим квадратик Нска (верхний левый угол), а всё остальное пространство будет занимать Москва. При этом, как и раньше, Нск будет неподвижен, а Москва будет рисоваться слоем ниже, на ней будут работать кнопки приближения, balloon'ы. Я долго и мучительно пробовал скрывать MapView при переходе во второй фрагмент, но максимум смог изменить его размеры, и то это работает непонятно когда.
Если не загружать первый фрагмент, а сразу переходить ко второму, то карта выводится в полный экран и полностью работает.
Переводить проект от фрагментов к активностям из-за этого пока не хочется.

Версия библиотеки достаточно старая, но с новой во втором пункте (про Philips) ничего не изменилось. Сначала думал, что забываю снимать listener'ы, но если даже просто минимально загрузить карту и ничего с ней не делать, всё равно, одна отображается поверх другой.

**Comment by punksta** [comment]
Встречался с проблемой, похожей на вторую. 
Помог вызов invalidate на вью navigation drawer(левое меню) из метода Activity::onStart

**Comment by saint13** [comment]
Попробуйте использовать tag=static, это есть в примере.

28 февр. 2017 г. 17:46 пользователь "Stanislav Shakirov" <
notifications@github.com> написал:

**Comment by CoolMind** [comment]
@punksta, @saint13: спасибо за помощь. Я ранее встречал при поиске этот атрибут, но не думал, что поможет. По крайней мере, третья проблема устранилась.
Атрибут android:tag="static" решил проблему. Разницы по скорости загрузки пока не заметил.
