### ISSUE TITLE
setZoomToSpan или setPositionNoAnimationTo позиционируют на карте лишь спустя секунду

### ISSUE THREAD

**Issue by CoolMind** [yandexmobile/yandexmapkit-android#261]
Здравствуйте!

```
mapController.setZoomToSpan(...);
mapController.setPositionNoAnimationTo(...);
mapController.notifyRepaint();
```

После выполнения карта показывает текущее положение пользователя, а не то, которое хочу. Если выполнить спустя секунду, то показывает так, как надо. Аналогично https://github.com/yandexmobile/yandexmapkit-android/issues/78. Карты в приложении старые, не знаю, исправлена ли эта ошибка в новых версиях.

**Comment by saint13** [comment]
А можно весь код.?

2 мар. 2017 г. 16:43 пользователь "Alexander" <notifications@github.com>
написал:

**Comment by CoolMind** [comment]
Только сейчас заметил, что если ничего не трогать, то через несколько секунд после этого карта сама по себе с анимацией переносит в ту точку, где нахожусь.
Вам какой код показать? Могу туда конкретные числа вписать, код создания карты написать.

**Comment by saint13** [comment]
Тогда все ясно. Происходит скоро к место положению. Вам нужно его
отключить.

2 мар. 2017 г. 19:38 пользователь "Alexander" <notifications@github.com>
написал:

**Comment by CoolMind** [comment]
Спасибо за комментарий. Дело в том, что на карте есть кнопка перехода к текущему местоположению (предусмотрена в ТЗ), есть код вида:
```
MyLocationOverlay myLocation = mOverlayManager.getMyLocation();
myLocation.setEnabled(true);
myLocation.addMyLocationListener(this);
```
Его отключение ничего не меняет.

**Comment by saint13** [comment]
Посмотри метод autoscroll только он один тебе нужен.

2 мар. 2017 г. 20:34 пользователь "Alexander" <notifications@github.com>
написал:

**Comment by CoolMind** [comment]
Не знаю, что это за метод, не нашёл такого.

**Comment by saint13** [comment]
setAutoScroll у MyLocationOverlay, отключает  авто скрол к локации

**Comment by CoolMind** [comment]
Спасибо, ещё потестирую. Странно, не заметил сразу аналогичный https://github.com/yandexmobile/yandexmapkit-android/issues/162.
