### ISSUE TITLE
Cache определенной области

### ISSUE THREAD

**Issue by vaniakerer** [yandexmobile/yandexmapkit-android#265]
Такое у вас возможно?
https://github.com/yandexmobile/yandexmapkit-android/issues/193

**Comment by saint13** [comment]
Такого апи нет. Но если пользователь работает с приложением в какой-то
области то эти данные складываются в кеш. И далее берутся из Кеша.

21 мар. 2017 г. 14:51 пользователь "Kerer Ivan" <notifications@github.com>
написал:
