### ISSUE TITLE
API для бизнеса

### ISSUE THREAD

**Issue by nikolleto** [yandexmobile/yandexmapkit-android#269]
Добрый день.
Не так давно Яндекс ужесточил [требования](https://tech.yandex.ru/maps/doc/jsapi/2.1/terms/index-docpage?from=mapsapi) для бесплатного API. Будет ли yandexmapkit-android работать с ключем API для бизнеса?

**Comment by saint13** [comment]
На текущую версию мапкита это не распространяется. Если будут изменения то
обязательно сообщим.

2 мая 2017 г. 15:25 пользователь "Nikolay Galizin" <notifications@github.com>
написал:

**Comment by nikolleto** [comment]
Не распространяется, значит, ключ API для бизнеса не будет работать с библиотекой, правильно я понял?

**Comment by saint13** [comment]
Для мапкита необходим свой ключ. Как он пересекается с бизнес, у меня
информации нет. Но на сколько мне известно на мапкит данные условия пока не
распространяются.

2 мая 2017 г. 15:42 пользователь "Nikolay Galizin" <notifications@github.com>
написал:

**Comment by nikolleto** [comment]
@saint13 Понятно, благодарю за оперативный ответ.

**Comment by PlatinumKiller** [comment]
Задрали, вы что не можете приватное апи использовать? Эти идиоты его вам дают.


Вторник,  2 мая 2017, 16:12 +03:00 от Nikolay Galizin <notifications@github.com>:
