### ISSUE TITLE
Android Studio 3.0 + gradle 4.0 + gradle pugin 3.0-alpha

### ISSUE THREAD

**Issue by Defuera** [yandexmobile/yandexmapkit-android#274]
Не подтягивается зависимость, когда пытаюсь подключить yandexmapkit в проекте, открытом в Android Studio 3.0 + gradle pugin 3.0-alpha. 

В условиях того же самого проект в ветке с gradle 3.3, gradle plugin версии 2.3.3 и AS 2.3 все работает как и ожидается.

Что делаю, что бы подключить?
1. Добавляю allprojects {    repositories {        maven { url 'https://github.com/yandexmobile/yandexmapkit-android/raw/maven/' }    }} в корневой build.gradle
1. Добавляю compile 'ru.yandex:yandexmapkit:2.5.4@aar' в app/build.gradle
 
Что значит не подтягивается?
IDE при наводе мышки на строчку `ru.yandex.yandexmapkit.MapView` пишет "cannot resolve symbol 'MapView'"

**Comment by saint13** [comment]
Спасибо посмотрим что не так.

14 июн. 2017 г. 23:53 пользователь "Denis Volyntsev" <
notifications@github.com> написал:

**Comment by Defuera** [comment]
обновил gradle plugin до `3.0.0-alpha4` и сам gradle до `4.0-rc-1` - без изменений

**Comment by Defuera** [comment]
Походу проблема в студии 3.0. Вот [тут](https://developer.android.com/studio/build/gradle-plugin-3-0-0.html) написано `dependencies on local AAR files are not yet supported.`. Хотя в нашем случае зависимость не локальная, но возможно это как то связано?

**Comment by rostopira** [comment]
AS 3.0 beta 2, автокомплит есть но при запуске вываливает

java.lang.ClassNotFoundException: Didn't find class "ru.yandex.yandexmapkit.MapView" on path: DexPathList

И это вообще без кода, просто добавлена карта в xml

**Comment by Mozgus** [comment]
Та же самая проблема (AndroidStudio 3.0 Beta 2) Просто добавляю карту в xml и всё рушится
`ClassNotFoundException: Didn't find class "com.package.name.MainActivity" on path: DexPathList[[zip file "/data/app/com.package.name-1/base.apk"],nativeLibraryDirectories=[/data/app/com.package.name-1/lib/arm64, /vendor/lib64, /system/lib64]]`
Сделайте что-нибудь или подскажите, каким путём решить...

**Comment by rostopira** [comment]
@Mozgus я откатился к стабильной АС 2.3, может с релизом 3.0 всё будет нормально
