### ISSUE TITLE
На Xiaomi Redmi Note 4 при анимации возврата с Activity карта перекрывает все другие элементы интерфейса

### ISSUE THREAD

**Issue by Syjgin** [yandexmobile/yandexmapkit-android#281]
Есть Activity с TabLayout. В одном табе - список магазинов, в другом - карта. При выборе магазина из списка при проигрывании анимации возврата к предыдущему экрану (после startActivityForResult) карта отображается так, как будто второго таба нет. Понятно, что это очень специфическая ситуация, но чем это может быть вызвано и можно ли как-то исправить?

**Comment by saint13** [comment]
Используйте tag в xml для MapView

android:tag="static"
