### ISSUE TITLE
Очень сильно лагает при любом взаимодействии с картой

### ISSUE THREAD

**Issue by adolgiy** [yandexmobile/yandexmapkit-android#290]
Привет. Сделал тестовое приложение: просто `MapView` на весь экран и все. Результат: при каждом перемещения - фризы, при зуме - то же самое. ApiKey получен. Nexus 6p, Android O.

**Comment by saint13** [comment]
Попробуй указать в xml у mapView android:tag="static"

**Comment by adolgiy** [comment]
@saint13 стало сильно лучше, спасибо!
