### ISSUE TITLE
Как  сделать  что бы иконка местоположения пользователя не изменялась при движении?

### ISSUE THREAD

**Issue by gerasimovdmitriy** [yandexmobile/yandexmapkit-android#292]
Сейчас когда стоишь на месте отображается иконка ymk_user_location_lbs (Буква Я в красном круге), а когда начинаешь движение начинает отображаться иконка  ymk_user_location_gps ( буква я в красной стрелке) и поворачивается по направлению движения.  Можно ли сделать так что бы в любом случае отображалась иконка  ymk_user_location_lbs и не поворачивалась по направлению движения?

**Comment by saint13** [comment]
При этом вы хотите получить координаты от gps  ? Если так что Вам легче самим реализовать отображения локации.

**Comment by gerasimovdmitriy** [comment]
Не подскажете как лучше всего это реализовать?

**Comment by gerasimovdmitriy** [comment]
Разобрался. Спасибо.
