### ISSUE TITLE
Как показать все точки, которые помещены на карту?

### ISSUE THREAD

**Issue by alinaSibiryakova** [yandexmobile/yandexmapkit-android#293]
Добрый день! Необходимо задать такой масштаб карты при котором все точки, помещенные на нее будут умещаться на экран устройства. Есть ли такой метод в yandex mapkit? setZoomToSpan не работает. В него передается точка. А этого явно не достаточно, чтобы обозначить область. 
На SGS8+ sample не работает.

**Comment by saint13** [comment]
Посмотрите в примере 

https://github.com/yandexmobile/yandexmapkit-android/blob/master/yandexmapkit-sample/src/ru/mapkittest/zoomspan/ZoomSpanActivity.java

**Comment by alinaSibiryakova** [comment]
@saint13 Смотрела. И сразу написала, что setZoomToSpan не работает. Даже если произвести расчеты как в упомянутом Вами примере. Зум получается таким, что видны лишь точки в середине области. У меня за границами экрана остаются еще точки.

**Comment by saint13** [comment]
В примере можете добавить небольшую дельту, что граничные элементы были
видны.

20 сент. 2017 г. 16:39 пользователь "alinaSibiryakova" <
notifications@github.com> написал:
