### ISSUE TITLE
Перестала грузиться карта, на различных устройствах

### ISSUE THREAD

**Issue by alekseisivkov** [yandexmobile/yandexmapkit-android#298]
Вчера (6 декабря) вечером перестали подгружаться тайлы карты, если они не были до этого закешированы.
Насколько знаю - очень много продуктовых приложений пострадало от этой проблемы.
Что делать? Известна ли проблема?

**Comment by kanat** [comment]
+1
Заметили сегодня. Сэмплы тоже не работают.

**Comment by hsander** [comment]
Да, карты не загружаются(

**Comment by RageTF** [comment]
жиза

**Comment by simtm** [comment]
аналогичная проблема. Не понятно ждать фикса или переезжать на google maps

**Comment by saint13** [comment]
Спасибо. Будем смотреть что случилось.

7 дек. 2017 г. 17:15 пользователь "Sidorov Mikhail" <
notifications@github.com> написал:

**Comment by avchukhov** [comment]
Протух сертификат на https://api.mobile.maps.yandex.net/

**Comment by saint13** [comment]
Проверяйте

7 дек. 2017 г. 17:54 пользователь "avchukhov" <notifications@github.com>
написал:

**Comment by saint13** [comment]
Чиним.

7 дек. 2017 г. 18:25 пользователь "Max mksaint" <mksaint13@gmail.com>
написал:

**Comment by saint13** [comment]
Готово

7 дек. 2017 г. 18:28 пользователь "Max mksaint" <mksaint13@gmail.com>
написал:

**Comment by dyap** [comment]
Работает. Спасибо.

**Comment by alekseisivkov** [comment]
Заработало, спасибо
