### ISSUE TITLE
ApiKey не читается из файла ресурсов

### ISSUE THREAD

**Issue by d-tarasov** [yandexmobile/yandexmapkit-android#90]
Если атрибуту `apiKey` элемента `MapView` в качестве значения ключа указать строковый ресурс, то он не воспринимается элементом. При этом в `LogCat` любые сообщения, которые могли бы навести на мысль так же отсутствуют. Проект собирается, активити запускается, но карта, информация о текущем местоположении или пробках не загружается.

```
<!-- Работает -->
<!-- layout.xml -->
<ru.yandex.yandexmapkit.MapView
    android:id="@+id/map_view"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:apiKey="1234567890"/>

<!-- Не работает -->
<!-- layout.xml -->
<ru.yandex.yandexmapkit.MapView
    android:id="@+id/map_view"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:apiKey="@string/key"/>

<!-- strings.xml -->
<string name="key">1234567890</string>
```

**Comment by Tsymlov** [comment]
Спасибо большое! Полтора часа искал решение. Кто бы мог подумать...
